import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Col, Container,Row ,Card} from 'react-bootstrap'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className={styles.Subtitle}>
           <h1>India #1 Platform for Casual social betting</h1>
           <p>Bet on absolutely anything and everything with other or with your friends for fun without risking your hard
earned money! Bets placed are for entertainment purposes only</p>
        </div>
    
        <Row>
          <Col xs={12} md={4}>
          <div className={styles.betRule}>
            <div className={styles.textHead}>
            <h2>1. Choose a Bet</h2>
            <p>You can either bet on Yes or No ,
Winner will double their earnings</p>
</div>
<div className={styles.betImg}>
  <img src="/assests/choice.png" alt="img"></img>
</div>
          </div>

          <div className={styles.betRule}>
          <div className={styles.textHead}>
          <h2>2. Place your Bet</h2>
          <p>You can either bet on Yes or No ,
Winner will double their earnings</p>
</div>
<div className={styles.betImg}>
  <img src="/assests/bet.png" alt="img"></img>
</div>
          </div>

          <div className={styles.betRule}>
          <div className={styles.textHead}>
          <h2> 3. Claim Rewards</h2>
          <p>You can either bet on Yes or No ,
Winner will double their earnings</p>
</div>
<div className={styles.betImg}>
  <img src="/assests/salary.png" alt="img"></img>
</div>
          </div>

          </Col>
          <Col xs={12} md={8} className={styles.margin34}>
            <div className={styles.text48}>Choose a module </div>
            <Row className={styles.hje}>
            <Card className={styles.cardBg}>
  <Card.Body>
    <Card.Title className={styles.cardTitle}>MI to Beat CSK</Card.Title>
    
    <Card.Text className={styles.cardSubTitle}>
    Will Mumbai Indians beat Chennai
Super Kings?
    </Card.Text>
    <div className={styles.betNow}>
    <Card.Link className={styles.cardYes} href="#">Yes</Card.Link>
    <Card.Link className={styles.cardNo} href="#">No</Card.Link>
    </div>
  </Card.Body>
  <h5 className={styles.hjw92}>Play in Public Leagues</h5>
</Card>

 <span className={styles.felo23}>or</span>

 <Card className={styles.cardBg}>
  <Card.Body>
    <Card.Title className={styles.cardTitle}>MI to Beat CSK</Card.Title>
  
    <Card.Text className={styles.cardSubTitle}>
    Will Mumbai Indians beat Chennai
Super Kings?
    </Card.Text>
    <div className={styles.betNow}>
    <Card.Link className={styles.cardYes} href="#">Yes</Card.Link>
    <Card.Link className={styles.cardNo} href="#">No</Card.Link>
    </div>
  </Card.Body>
  <h5 className={styles.hjw92}>Play with your friends</h5>
</Card>

</Row>

          </Col>
        </Row>
      </Container>
      

 
    </div>
  )
}
